- name: Configure Backend Server
  hosts: backend
  become: yes

  vars:
  
    backend_zip_url: "https://expense-joindevops.s3.us-east-1.amazonaws.com/expense-backend-v2.zip"

  tasks:

    # ---------------- NODEJS --------------------
    - name: Disable default nodejs module
      ansible.builtin.command: dnf module disable nodejs -y

    - name: Enable nodejs:20 module
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install NodeJS
      ansible.builtin.package:
        name: nodejs
        state: present

    # ---------------- USER + APP DIRECTORY --------------------
    - name: Create expense user
      ansible.builtin.user:
        name: expense
        system: yes
        shell: /sbin/nologin

    - name: Create app directory
      ansible.builtin.file:
        path: /app
        state: directory
        owner: expense
        group: expense
        mode: '0755'

    # ---------------- APP SETUP --------------------
    - name: Download backend application
      ansible.builtin.get_url:
        url: "{{ backend_zip_url }}"
        dest: /tmp/backend.zip

    - name: Extract backend application
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app/
        remote_src: yes

    - name: Install nodejs dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app
      become_user: expense

    # ---------------- MYSQL --------------------
    - name: Install mysql client
      ansible.builtin.package:
        name: mysql
        state: present

    - name: Load backend schema
      ansible.builtin.command: >
        mysql -h {{ mysql_host }} -uroot -pExpenseApp@1 < /app/schema/backend.sql

    # ---------------- BACKEND SERVICE --------------------
    - name: Start backend service
      ansible.builtin.command: systemctl start backend

    - name: Enable backend service
      ansible.builtin.command: systemctl enable backend

    - name: Restart backend service
      ansible.builtin.command: systemctl restart backend
