- name : configure frontend server
  hosts : frontend
  become : yes
  tasks : 
  - name : install nginx
    ansible.builtin.command : dnf install nginx -y 

  - name : enable nginx
    ansible.builtin.command : systemctl enable nginx

  - name : start nginx 
    ansible.builtin.command  : systemctl start nginx

  - name : remove html directory
    ansible.builtin.file:
    state : absent
    path :  /usr/share/nginx/html/*

  - name : download frontend application 
    ansible.builtin.get_url:
    url : curl -o /tmp/frontend.zip https://expense-joindevops.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest : /tmp/frontend.zip

  - name : extract frontend application
    ansible.builtin.unarchive:
      src : /tmp/frontend.zip
      dest : /usr/share/nginx/html/
      remote_src : yes

  - name : delete default nginx configure
    ansible.builtin.file : 
      state : absent
      path : /etc/nginx/expense.conf

  - name : copy nginx conf 
    ansible.builtin.copy : 
      src : expense.conf 
      dest : /etc/nginx/default.d/expense.conf
      overwrite : yes
  
  - name : restart nginx
    ansible.builtin.service : 
      name : nginx
      state : restarted
      enabled : yes
